routes:
    home: 'Default:home'
    form: 'Default:form'
    authToken: 'Default:authToken'
    dbTest : 'Default:dbTest'
    confirmForm: 'Default:confirmForm'
    accessToken: 'Default:accessToken'
    userCreation: 'User:register'

defaut_route: 'form'
